import { useCallback, useState, useRef, useEffect } from 'react';
import jsPDF from 'jspdf';

function buildPDF(destination, itinerary) {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pw = pdf.internal.pageSize.getWidth();
  let y = 20;
  const mr = 15;
  const mw = pw - mr * 2;

  pdf.setFontSize(22);
  pdf.text(destination || 'Travel Itinerary', mr, y);
  y += 8;
  pdf.setFontSize(11);
  pdf.setTextColor(100, 116, 139);
  pdf.text('Generated by SarthiAI', mr, y);
  y += 12;

  if (!itinerary?.days) { return pdf; }

  itinerary.days.forEach((day, di) => {
    if (y > 250) { pdf.addPage(); y = 20; }

    pdf.setDrawColor(99, 102, 241);
    pdf.setFillColor(99, 102, 241);
    pdf.roundedRect(mr, y, 8, 8, 2, 2, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(9);
    pdf.text(String(di + 1), mr + 2.5, y + 6);
    pdf.setTextColor(30, 41, 59);
    pdf.setFontSize(14);
    pdf.text(`Day ${di + 1}`, mr + 13, y + 7);
    y += 14;

    day.activities?.forEach((act) => {
      if (y > 255) { pdf.addPage(); y = 20; }

      pdf.setFontSize(10);
      pdf.setTextColor(148, 163, 184);
      pdf.text(act.time || '', mr, y);
      pdf.setTextColor(30, 41, 59);
      pdf.setFontSize(11);
      const title = act.title || '';
      pdf.text(title, mr + 18, y);
      y += 5.5;

      pdf.setFontSize(9);
      pdf.setTextColor(100, 116, 139);
      const desc = act.description || '';
      const lines = pdf.splitTextToSize(desc, mw);
      lines.forEach((l) => {
        if (y > 260) { pdf.addPage(); y = 20; }
        pdf.text(l, mr, y);
        y += 4;
      });

      const meta = [];
      if (act.duration) meta.push(`Duration: ${act.duration}`);
      if (act.estimated_cost) meta.push(`Cost: ${act.estimated_cost}`);
      if (act.category) meta.push(`Category: ${act.category}`);
      if (meta.length) {
        pdf.setTextColor(148, 163, 184);
        pdf.setFontSize(8);
        pdf.text(meta.join('  •  '), mr, y);
        y += 4;
      }

      if (act.tips) {
        if (y > 260) { pdf.addPage(); y = 20; }
        pdf.setTextColor(217, 119, 6);
        pdf.setFontSize(8);
        pdf.text(`Tip: ${act.tips}`, mr, y);
        y += 4;
      }

      y += 3;
    });
    y += 4;
  });

  pdf.setTextColor(148, 163, 184);
  pdf.setFontSize(8);
  pdf.text('Powered by SarthiAI', mr, pdf.internal.pageSize.getHeight() - 10);

  return pdf;
}

export default function PDFExportButton({ destination, itinerary }) {
  const [showShare, setShowShare] = useState(false);
  const ref = useRef(null);
  const [sharing, setSharing] = useState(false);

  useEffect(() => {
    const handler = (e) => { if (ref.current && !ref.current.contains(e.target)) setShowShare(false); };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, []);

  const download = useCallback(() => {
    const pdf = buildPDF(destination, itinerary);
    pdf.save(`${destination || 'itinerary'}.pdf`);
  }, [destination, itinerary]);

  const share = useCallback(async () => {
    setShowShare(false);
    setSharing(true);
    try {
      const pdf = buildPDF(destination, itinerary);
      const blob = pdf.output('blob');
      const file = new File([blob], `${destination || 'itinerary'}.pdf`, { type: 'application/pdf' });

      if (navigator.canShare && navigator.canShare({ files: [file] })) {
        await navigator.share({ files: [file], title: `${destination} Itinerary` });
      } else {
        pdf.save(`${destination || 'itinerary'}.pdf`);
      }
    } catch (err) {
      if (err.name !== 'AbortError') {
        const pdf = buildPDF(destination, itinerary);
        pdf.save(`${destination || 'itinerary'}.pdf`);
      }
    }
    setSharing(false);
  }, [destination, itinerary]);

  return (
    <div className="flex justify-center mt-8 mb-6 gap-3 no-print" ref={ref}>
      <button onClick={download} disabled={sharing} className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-indigo-500 hover:bg-indigo-600 text-white text-sm font-medium transition shadow-md shadow-indigo-200 cursor-pointer disabled:opacity-50">
        <svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" /><polyline points="14 2 14 8 20 8" />
          <line x1="16" y1="13" x2="8" y2="13" /><line x1="16" y1="17" x2="8" y2="17" />
        </svg>
        Download PDF
      </button>

      <div className="relative">
        <button onClick={() => setShowShare(!showShare)} disabled={sharing} className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-white hover:bg-slate-50 text-slate-700 text-sm font-medium transition border border-slate-200 shadow-sm cursor-pointer disabled:opacity-50">
          <svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <circle cx="18" cy="5" r="3" /><circle cx="6" cy="12" r="3" /><circle cx="18" cy="19" r="3" />
            <line x1="8.59" y1="13.51" x2="15.42" y2="17.49" /><line x1="15.41" y1="6.51" x2="8.59" y2="10.49" />
          </svg>
          {sharing ? 'Generating...' : 'Share'}
        </button>

        {showShare && (
          <div className="absolute bottom-full mb-3 left-1/2 -translate-x-1/2 bg-white rounded-2xl border border-slate-100 shadow-xl shadow-slate-200/50 p-2 min-w-[220px] animate-fade-in">
            <p className="text-[11px] font-medium text-slate-400 uppercase tracking-wider px-3 pt-1 pb-2">Share</p>
            <div className="flex gap-2 justify-center pb-2">
              <button onClick={share} className="flex flex-col items-center gap-1 px-4 py-2 rounded-xl hover:bg-blue-50 text-sm transition group w-20">
                <span className="w-10 h-10 rounded-full bg-blue-50 flex items-center justify-center text-lg group-hover:scale-110 transition-transform">✉️</span>
                <span className="text-[11px] text-slate-500">Email</span>
              </button>
              <button onClick={share} className="flex flex-col items-center gap-1 px-4 py-2 rounded-xl hover:bg-green-50 text-sm transition group w-20">
                <span className="w-10 h-10 rounded-full bg-green-50 flex items-center justify-center text-lg group-hover:scale-110 transition-transform">💬</span>
                <span className="text-[11px] text-slate-500">WhatsApp</span>
              </button>
              <button onClick={share} className="flex flex-col items-center gap-1 px-4 py-2 rounded-xl hover:bg-slate-50 text-sm transition group w-20">
                <span className="w-10 h-10 rounded-full bg-slate-50 flex items-center justify-center text-lg group-hover:scale-110 transition-transform">➕</span>
                <span className="text-[11px] text-slate-500">More</span>
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
